name: SPTestForRBAC
on:
    workflow_dispatch:    



permissions:
      id-token: write
      contents: read
jobs:
  Test-SevicePrincipal:
    runs-on: ubuntu-latest
    environment:
        name: RBAC
    steps:   
      # log in to Azure using OpenID Connect
      
      - name: 'Az login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



      - name: Run
        if: ${{ true }}
        run: |
          ClientId=$(az ad app create --display-name AditiRBAC --query appId --output tsv)
          az ad sp create --id $ClientId 
          az ad app federated-credential create --id $ClientId --parameters '{"name":"GitHUB_OICD","issuer":"https://token.actions.githubusercontent.com/","subject":"repo:org/repo:environment:Sample-Env1","description":"TestEnv","audiences":["api://AzureADTokenExchange"]}'
          
